### ISSUE TITLE
“Goto symbol…”

### ISSUE THREAD

**Issue by Hibou57** [steinwaywhw/ats-mode-sublimetext#14]
The syntax definition does not defines the selectors needed for “Goto symbol…”  to work. I just wanted to know if it's on purpose or not.

I started to write my own ATS syntax definition for Sublime Text, when I discovered there were already one, so I will use the already existing one. I may try to change the definition so that it defines the required selectors.

If any one wants to comment on this, you can tell.

**Comment by Hibou57** [comment]
I've just made a pull request for the change made in my fork.

**Comment by steinwaywhw** [comment]
Merged.
