### ISSUE TITLE
Universal quantifier may not be highlighted

### ISSUE THREAD

**Issue by Hibou57** [steinwaywhw/ats-mode-sublimetext#16]
I will try to solve it (it was already so before my pull request): quantifiers sometimes, are not highlighted.

In this case, the first `{A}` is not highlighted:

    implement
    impl_trans
      {A}{B}{C} (pf1, pf2) =
      impl_intr (lam pf => impl_elim (pf2, impl_elim (pf1, pf)))

In this case however, the first `{A}` is highlighted:

    implement 
    impl_trans {A}{B}{C} (pf1, pf2) =
      impl_intr (lam pf => impl_elim (pf2, impl_elim (pf1, pf)))

In the second case, its scope is `support.type`, in the first case, it is assigned no scope at all.

**Comment by Hibou57** [comment]
Fixed with https://github.com/Hibou57/ats-mode-sublimetext/commit/656ac48ca3618ea89d733368a60d6c47cc83de32

**Comment by steinwaywhw** [comment]
Merged.
