### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [steinwaywhw/ats-mode-sublimetext#18]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by steinwaywhw** [comment]
Thanks for letting me know. It's now MIT, https://github.com/steinwaywhw/ats-mode-sublimetext/commit/b4f5a7a9ceaf257ada89cb1068fb170db51cd426
