### ISSUE TITLE
Having ats-mode-sublimetext on ats-lang/Resources

### ISSUE THREAD

**Issue by githwxi** [steinwaywhw/ats-mode-sublimetext#6]
Hi Hanwen,

Could you add an item about ats-mode-sublimetext in the following file
and then issue a git-pull request:

https://github.com/githwxi/ATS-Postiats/blob/master/doc/PROJECT/MEDIUM/ats2langweb/thePageRBodyRight/Resources.php

Also, could you mention in README.md how ats-mode-sublimetext can/should be used. I will recommend it to the students taking CS520 next week.

**Comment by steinwaywhw** [comment]
Sure
