### ISSUE TITLE
{...} needs to be properly handled

### ISSUE THREAD

**Issue by githwxi** [steinwaywhw/ats-mode-sublimetext#8]
The current handling of {...} is incorrect:

```ats
implement ats_serial_tx_vect () =
  if ringbuf_is_empty tx_buffer then {
    // Buffer empty, so disable interrupts
    val () = c_cbi (ADDR_UCSRB, BIT_UDRIE)
  } else {
    // There is more data in the output buffer. Send the next byte
    val c  = ringbuf_remove tx_buffer
    val () = $UN.ptr0_set<uchar> (ADDR_UDR, c)
  }
```

**Comment by steinwaywhw** [comment]
ok. I currently recognize {} as block of code when it is prepended by `where|=|^`, `^` matches line beginning. Now I will add `then|else`. Is there other cases I should also include?

**Comment by githwxi** [comment]
In ATS, there are the following ways of using {...}

1) where { decls }
2) $rec { a= ..., b= ..., c= ... }
3) $rec_vt { a= ..., b= ..., c= ... }
4) { decls }

decls means a list of declarations. If we write { decls }, it means 'let decls in (*empty*) end'.

**Comment by steinwaywhw** [comment]
Ok, fixed. But it takes time to be pushed into Github. SublimeText should work within one hour though.

**Comment by steinwaywhw** [comment]
it appears to be rolled out now.

**Comment by githwxi** [comment]
Cool!
